# config/meta.yml

meta_product_name: "Socialive"
meta_title: "Socialive - Livestreams that matter"
meta_description: "Welcome to Socialive, a place to watch private livestreams and interact with the influencers that matter most to you."
meta_image: "cinema.jpg"                           # Une image dans votre dossier app/assets/images/
twitter_account: "@socialivetv"              # indispensable pour les Twitter Cards
